Docs/aire
lac-analytics/gdlaire pull request #39
Opened 2020-12-13 20:35 UTC by edgaregurrola

Revisión a la metodología de limpieza de datos de calidad del aire y reescrito de la metodología para el cálculo de las emisiones en edificios gubernamentales.

2020-12-14 08:39 UTC, nateraluis requested changes
Ya le dí una revisada @edgaregurrola Lo veo muy bien, solamente encontre un par de detalles cuando se ponen los links, en markdown para que reconozca que es un link tiene que estar el texto dentro de los corchetes y el url pegado dentro de los paréntesis, sin espacio entre corchetes y paréntesis:
`[texto](URL)` --> Link activo
`[texto] (URL)` --> Se renderea como [texto] (URL) separados y el link queda activo dentro de los parentesis
Creo que una vez que hagamos este merge ya estamos del otro lado, les enviare los materiales y demás para que le den una revisada y ver si podemos ya cerrar el proyecto esta semana o inicios de la siguiente a más tardar.

2020-12-14 08:39 UTC, nateraluis commented on output/text/analisis.md
> ++ Localización de edificios gubernamentales: El primer paso fue obtener la ubicación de los sitios gubernamentales utilizando la base de datos georreferenciada del [Directorio Estadístico de Unidades
Los links en markdown no tienen que llevar espacio entre `[texto](link)` para que queden como link activo, sino queda como un texto dentro de los corchetes y la url dentro del paréntesis.
Lo puedes corregir @edgaregurrola 
Gracias!

2020-12-14 08:39 UTC, nateraluis commented on output/text/analisis.md
> ++ Descarga de edificaciones: Utilizando la base de datos de [OpenStreetMap] (https://www.openstreetmap.org/#map=6/23.944/-102.579) y el módulo [OSMnx] (https://osmnx.readthedocs.io/en/stable/) para P
Mismo issue con los links `[texto](url)`

2020-12-14 08:39 UTC, nateraluis commented on output/text/analisis.md
> ++ Cálculo del consumo energético: Con el dato de m² estimados de edificios gubernamentales para cada estación de MiMacro Periférico se realizó el cálculo del consumo energético, multiplicando los m²
Link

2020-12-14 08:39 UTC, nateraluis commented on output/text/analisis.md
> ++ Cálculo de emisiones: Por último, el consumo energético por edificio en unidades kWh/yr se multiplicó por la estimación de emisiones de CO₂ de [Google.org Enviromental Insights Explorer] (https://i
Link

2020-12-14 08:39 UTC, nateraluis commented on output/text/analisis.md
> +Para el cálculo se realizó un recorte de las vialidades cercanas a las estaciones y se agregó el valor total de la distancia (en m) a cada estación. Posteriormente, para cada estación se definió el m
Link de Google EIE.

2020-12-15 05:31 UTC, edgaregurrola commented on output/text/analisis.md
> ++ Cálculo de emisiones: Por último, el consumo energético por edificio en unidades kWh/yr se multiplicó por la estimación de emisiones de CO₂ de [Google.org Enviromental Insights Explorer] (https://i
Ya quedaron corregidas las observaciones y hay nuevos commits que colocan los mapas que faltaban en las emisiones de edificios y se agregan los textos para las secciones de limitantes y siguientes pasos.
En otros commits viene una reestructuración de la metodología del cálculo de las emisiones por transporte para que coincida con la de las emisiones, también se agregan mapas y se incorporan las secciones de limitantes y siguientes pasos.

2020-12-15 08:06 UTC, nateraluis approved these changes
Perfecto, muchas gracias @edgaregurrola!

2020-12-15 08:12 UTC, merged